name: base-pipeline

on:
  workflow_dispatch:

jobs:
  # Apply Infrastructure configurations when action=='create'.
  snyk:
    name: Code security scan
    uses: filipefigueredo/nestjs-postgres-task-crud/.github/workflows/snyk-code-scan.workflow.yaml@master
    with:
      language-tooling: nodejs
    secrets:
      snyk_api_token: ${{ secrets.SNYK_API_TOKEN }}
